---
extends: airbnb
parserOptions:
  ecmaVersion: '6'
env:
  node: true
  mocha: true
rules:
  no-use-before-define: 'off'
  strict: 'off'
  comma-dangle: 'off'
  no-template-curly-in-string: 'off'
  import/no-extraneous-dependencies: 'off'
  no-param-reassign: 'off'
  prefer-spread: 'off'
  prefer-rest-params: 'off'
  max-len: ['error', 140, 2, {
      ignoreUrls: true,
      ignoreComments: false,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
    }]
